ban_kinh = float(input("nhap ban kinh:"))
dien_tich = float(input("nhap dien tich:"))
print("hinh co ban kinh ",ban_kinh," va co dien tich ",dien_tich)
ban_kinh2 = float(input("Nhap ban kinh can tinh toan :"))
dien_tich2 = 3,14 * (ban_kinh2**2)
print("hinh co ban kinh ",ban_kinh2," va co dien tich ",dien_tich2)